### PR TITLE
Kittiu enh translation on partner fields

### PR DESCRIPTION
**Pull request by kittiu**
Added translation=true on Partner name and Address

### CODE REVIEW

**Comment by kittiu** [comment]
http://128.199.123.133:10083/issues/195
http://128.199.123.133:10083/issues/196
http://128.199.123.133:10083/issues/197

**Comment by kittiu** [comment]
http://128.199.123.133:10083/issues/230

**Comment by yostashiro** [comment]
@kittiu As mentioned on Skype, below is what the customer form view will look like in production DB once we update the code in the server.

image

Please help follow up to update the code in the server (along with creating the language record) as it's probably better you handle the communication with the customer for this case.

**Comment by yostashiro** [comment]
@kittiu by the way, you plan to update the reports to reflect the changes in `l10n_th_address`, correct?  I guess there will be cases of address presentation becoming incomplete, otherwise, in case `street2` is used.

**Pull request merged**
